using System.Globalization;
using System.Text;
using EPLab.Compiler.Semantics;
using EPLab.Compiler.Syntax;

namespace EPLab.Compiler.CodeGen;

public sealed record GeneratedSource(string FileName, string Text);

public sealed class CSharpEmitter
{
    private readonly BoundProgram program;
    private int generatedName;
    private ClassDeclarationSyntax? currentClass;
    private MethodDeclarationSyntax? currentMethod;
    private IReadOnlyDictionary<string, string> hoistedLocals = new Dictionary<string, string>();

    public CSharpEmitter(BoundProgram program) => this.program = program;

    public IReadOnlyList<GeneratedSource> Emit()
    {
        List<GeneratedSource> sources = new()
        {
            new GeneratedSource("EPLab.Runtime.g.cs", EmitRuntime()),
            new GeneratedSource("EPLab.Program.g.cs", EmitProgram()),
        };
        if (program.Plugin is not null)
            sources.Add(new GeneratedSource("EPLab.LabApi.g.cs", EmitLabApiHost()));
        return sources;
    }

    private string EmitProgram()
    {
        IndentedWriter writer = new();
        writer.WriteLine("// <auto-generated by EPLab />");
        writer.WriteLine("#nullable enable");
        foreach (string import in DefaultImports.Concat(program.NamespaceImports).Distinct(StringComparer.Ordinal))
            writer.WriteLine($"using {NormalizeQualifiedName(import)};");
        writer.WriteLine($"using static {NormalizeQualifiedName(program.Project.RootNamespace)}.__EplGlobals;");
        writer.WriteLine();

        using (writer.Block($"namespace {NormalizeQualifiedName(program.Project.RootNamespace)}"))
        {
            EmitGlobals(writer);
            foreach (DeclarationSyntax declaration in program.Declarations)
            {
                switch (declaration)
                {
                    case ClassDeclarationSyntax @class:
                        EmitClass(writer, @class);
                        break;
                    case StructDeclarationSyntax structure:
                        EmitStruct(writer, structure);
                        break;
                    case EnumDeclarationSyntax enumeration:
                        EmitEnum(writer, enumeration);
                        break;
                }
            }
        }

        return writer.ToString();
    }

    private void EmitGlobals(IndentedWriter writer)
    {
        using (writer.Block("internal static class __EplGlobals"))
        {
            foreach (DeclarationSyntax declaration in program.Declarations)
            {
                switch (declaration)
                {
                    case FieldDeclarationSyntax field:
                        EmitField(writer, field, forceStatic: true);
                        break;
                    case ConstantDeclarationSyntax constant:
                        LineDirective(writer, constant.Span);
                        writer.WriteLine($"{VisibilityText(constant.Visibility)} static readonly {InferConstantType(constant.Value)} {Identifier(constant.Name)} = {EmitExpression(constant.Value)};");
                        ResetLineDirective(writer);
                        break;
                    case DllDeclarationSyntax dll:
                        EmitDll(writer, dll);
                        break;
                }
            }
        }
        writer.WriteLine();
    }

    private void EmitClass(IndentedWriter writer, ClassDeclarationSyntax @class)
    {
        currentClass = @class;
        string modifiers = DeclarationModifiersText(@class.Modifiers & (DeclarationModifiers.Abstract | DeclarationModifiers.Sealed | DeclarationModifiers.Partial));
        string baseType = @class.BaseType is null ? string.Empty : $" : {TypeText(@class.BaseType)}";
        string visibility = program.Plugin?.ConfigClassName?.Equals(@class.Name, StringComparison.OrdinalIgnoreCase) == true
            ? "public"
            : VisibilityText(@class.Visibility);
        LineDirective(writer, @class.Span);
        using (writer.Block($"{visibility} {modifiers}class {Identifier(@class.Name)}{baseType}".Replace("  ", " ")))
        {
            foreach (FieldDeclarationSyntax field in @class.Fields)
                EmitField(writer, field);

            Dictionary<MethodDeclarationSyntax, Dictionary<string, string>> hoistedByMethod = new();
            int hoistedOrdinal = 0;
            foreach (MethodDeclarationSyntax method in @class.Methods)
            {
                Dictionary<string, string> methodHoisted = new(StringComparer.OrdinalIgnoreCase);
                foreach (LocalVariableSyntax local in method.Locals.Where(static local => local.Modifiers.HasFlag(DeclarationModifiers.Static)))
                {
                    string fieldName = $"__静态_{Identifier(method.Name).TrimStart('@')}_{Identifier(local.Name).TrimStart('@')}_{++hoistedOrdinal}";
                    methodHoisted[local.Name] = fieldName;
                    bool lazyInitialize = NeedsLazyHoistedInitialization(local);
                    string initializer = !lazyInitialize
                        ? EmitInitializer(local.Type, local.ArrayShape, null)
                        : " = default!";
                    writer.WriteLine($"private static {TypeText(local.Type, local.ArrayShape is not null)} {fieldName}{initializer};");
                    if (lazyInitialize)
                        writer.WriteLine($"private static bool {HoistedInitializerFlag(fieldName)};");
                }
                hoistedByMethod[method] = methodHoisted;
            }

            if (@class.Fields.Count > 0 || hoistedByMethod.Values.Any(static map => map.Count > 0))
                writer.WriteLine();

            foreach (MethodDeclarationSyntax method in @class.Methods)
            {
                hoistedLocals = hoistedByMethod[method];
                EmitMethod(writer, method, @class.Name);
                writer.WriteLine();
            }
        }
        ResetLineDirective(writer);
        writer.WriteLine();
        currentClass = null;
        hoistedLocals = new Dictionary<string, string>();
    }

    private void EmitStruct(IndentedWriter writer, StructDeclarationSyntax structure)
    {
        LineDirective(writer, structure.Span);
        using (writer.Block($"{VisibilityText(structure.Visibility)} struct {Identifier(structure.Name)}"))
        {
            foreach (FieldDeclarationSyntax member in structure.Members)
                EmitField(writer, member);
        }
        ResetLineDirective(writer);
        writer.WriteLine();
    }

    private void EmitEnum(IndentedWriter writer, EnumDeclarationSyntax enumeration)
    {
        LineDirective(writer, enumeration.Span);
        using (writer.Block($"{VisibilityText(enumeration.Visibility)} enum {Identifier(enumeration.Name)}"))
        {
            foreach (EnumMemberSyntax member in enumeration.Members)
            {
                string value = member.Value is null ? string.Empty : $" = {EmitExpression(member.Value)}";
                writer.WriteLine($"{Identifier(member.Name)}{value},");
            }
        }
        ResetLineDirective(writer);
        writer.WriteLine();
    }

    private void EmitField(IndentedWriter writer, FieldDeclarationSyntax field, bool forceStatic = false)
    {
        LineDirective(writer, field.Span);
        DeclarationModifiers modifiers = field.Modifiers;
        if (forceStatic)
            modifiers |= DeclarationModifiers.Static;
        string modifierText = DeclarationModifiersText(modifiers & (DeclarationModifiers.Static | DeclarationModifiers.ReadOnly));
        writer.WriteLine($"{VisibilityText(field.Visibility)} {modifierText}{TypeText(field.Type, field.ArrayShape is not null)} {Identifier(field.Name)}{EmitInitializer(field.Type, field.ArrayShape, field.Initializer)};".Replace("  ", " "));
        ResetLineDirective(writer);
    }

    private void EmitDll(IndentedWriter writer, DllDeclarationSyntax dll)
    {
        LineDirective(writer, dll.Span);
        writer.WriteLine($"[System.Runtime.InteropServices.DllImport({StringLiteral(dll.LibraryName)}, EntryPoint = {StringLiteral(dll.EntryPoint)})]");
        writer.WriteLine($"{VisibilityText(dll.Visibility)} static extern {TypeText(dll.ReturnType)} {Identifier(dll.Name)}({string.Join(", ", dll.Parameters.Select(EmitParameter))});");
        ResetLineDirective(writer);
    }

    private void EmitMethod(IndentedWriter writer, MethodDeclarationSyntax method, string className)
    {
        currentMethod = method;
        LineDirective(writer, method.Span);
        bool constructor = method.Modifiers.HasFlag(DeclarationModifiers.Constructor) || method.Name == "_初始化";
        string signature;
        if (constructor)
        {
            signature = $"{MethodVisibilityText(method)} {Identifier(className)}({string.Join(", ", method.Parameters.Select(EmitParameter))})";
        }
        else
        {
            string modifiers = DeclarationModifiersText(method.Modifiers & ~DeclarationModifiers.Constructor);
            signature = $"{MethodVisibilityText(method)} {modifiers}{TypeText(method.ReturnType)} {Identifier(method.Name)}({string.Join(", ", method.Parameters.Select(EmitParameter))})".Replace("  ", " ");
        }

        using (writer.Block(signature))
        {
            foreach (LocalVariableSyntax local in method.Locals.Where(static local => !local.Modifiers.HasFlag(DeclarationModifiers.Static)))
            {
                LineDirective(writer, local.Span);
                writer.WriteLine($"{TypeText(local.Type, local.ArrayShape is not null)} {Identifier(local.Name)}{EmitInitializer(local.Type, local.ArrayShape, local.Initializer)};");
            }

            foreach (LocalVariableSyntax local in method.Locals.Where(static local => local.Modifiers.HasFlag(DeclarationModifiers.Static) && NeedsLazyHoistedInitialization(local)))
            {
                string fieldName = hoistedLocals[local.Name];
                LineDirective(writer, local.Span);
                using (writer.Block($"if (!{HoistedInitializerFlag(fieldName)})"))
                {
                    writer.WriteLine($"{fieldName} = {EmitLazyHoistedInitialValue(local)};");
                    writer.WriteLine($"{HoistedInitializerFlag(fieldName)} = true;");
                }
            }

            foreach (StatementSyntax statement in method.Statements)
                EmitStatement(writer, statement);

            if (!constructor && TypeText(method.ReturnType) != "void" && !DefinitelyReturns(method.Statements))
                writer.WriteLine($"return {DefaultValue(method.ReturnType)};");
        }
        ResetLineDirective(writer);
        currentMethod = null;
    }

    private void EmitStatement(IndentedWriter writer, StatementSyntax statement)
    {
        LineDirective(writer, statement.Span);
        switch (statement)
        {
            case EmptyStatementSyntax:
                writer.WriteLine();
                break;

            case AssignmentStatementSyntax assignment:
                TypeSyntax? assignmentType = ResolveExpressionType(assignment.Target);
                writer.WriteLine($"{EmitExpression(assignment.Target)} = {EmitExpressionForDestination(assignmentType, assignment.Value)};");
                break;

            case ExpressionStatementSyntax expression:
                EmitExpressionStatement(writer, expression.Expression);
                break;

            case IfStatementSyntax conditional:
                using (writer.Block($"if ({EmitExpression(conditional.Condition)})"))
                    foreach (StatementSyntax child in conditional.ThenStatements) EmitStatement(writer, child);
                if (conditional.ElseStatements.Count > 0)
                {
                    using (writer.Block("else"))
                        foreach (StatementSyntax child in conditional.ElseStatements) EmitStatement(writer, child);
                }
                break;

            case WhileStatementSyntax loop when loop.TestAfterBody:
                writer.WriteLine("do");
                writer.WriteLine("{");
                writer.Indent();
                foreach (StatementSyntax child in loop.Statements) EmitStatement(writer, child);
                writer.Unindent();
                writer.WriteLine($"}} while ({EmitExpression(loop.Condition)});");
                break;

            case WhileStatementSyntax loop:
                using (writer.Block($"while ({EmitExpression(loop.Condition)})"))
                    foreach (StatementSyntax child in loop.Statements) EmitStatement(writer, child);
                break;

            case CountLoopStatementSyntax count:
                EmitCountLoop(writer, count);
                break;

            case RangeLoopStatementSyntax range:
                EmitRangeLoop(writer, range);
                break;

            case ForEachStatementSyntax each:
                string eachType = each.VariableType is null ? "var" : TypeText(each.VariableType);
                using (writer.Block($"foreach ({eachType} {Identifier(each.VariableName)} in {EmitExpression(each.Collection)})"))
                    foreach (StatementSyntax child in each.Statements) EmitStatement(writer, child);
                break;

            case ChooseStatementSyntax choose:
                if (choose.Branches.Count == 0)
                {
                    // A default-only Easy choice is an unconditional block. Emitting
                    // `else` without a preceding `if` would produce invalid C#.
                    foreach (StatementSyntax child in choose.DefaultStatements) EmitStatement(writer, child);
                    break;
                }

                for (int i = 0; i < choose.Branches.Count; i++)
                {
                    ConditionalBranchSyntax branch = choose.Branches[i];
                    using (writer.Block($"{(i == 0 ? "if" : "else if")} ({EmitExpression(branch.Condition)})"))
                        foreach (StatementSyntax child in branch.Statements) EmitStatement(writer, child);
                }
                if (choose.DefaultStatements.Count > 0)
                {
                    using (writer.Block("else"))
                        foreach (StatementSyntax child in choose.DefaultStatements) EmitStatement(writer, child);
                }
                break;

            case TryStatementSyntax attempt:
                if (attempt.Catches.Count == 0 && attempt.FinallyStatements.Count == 0)
                {
                    // A handler-free try has no observable exception behavior of its
                    // own, so EPLab treats it as a grouping block. This also covers an
                    // explicitly empty `.\u6700\u7ec8` block, which is behaviorally identical.
                    foreach (StatementSyntax child in attempt.TryStatements) EmitStatement(writer, child);
                    break;
                }

                using (writer.Block("try"))
                    foreach (StatementSyntax child in attempt.TryStatements) EmitStatement(writer, child);
                foreach (CatchClauseSyntax clause in attempt.Catches)
                {
                    using (writer.Block($"catch ({TypeText(clause.ExceptionType)} {Identifier(clause.VariableName)})"))
                        foreach (StatementSyntax child in clause.Statements) EmitStatement(writer, child);
                }
                if (attempt.FinallyStatements.Count > 0)
                {
                    using (writer.Block("finally"))
                        foreach (StatementSyntax child in attempt.FinallyStatements) EmitStatement(writer, child);
                }
                break;

            case TemporarySetStatementSyntax temporary:
                EmitTemporarySet(writer, temporary);
                break;

            case LockStatementSyntax locked:
                using (writer.Block($"lock ({EmitExpression(locked.Target)})"))
                    foreach (StatementSyntax child in locked.Statements) EmitStatement(writer, child);
                break;

            case UsingStatementSyntax resource:
                using (writer.Block($"using (var {Identifier(resource.VariableName)} = {EmitExpression(resource.Value)})"))
                    foreach (StatementSyntax child in resource.Statements) EmitStatement(writer, child);
                break;

            default:
                writer.WriteLine($"throw new System.NotSupportedException({StringLiteral($"Unsupported EPLab statement: {statement.GetType().Name}")});");
                break;
        }
    }

    private void EmitExpressionStatement(IndentedWriter writer, ExpressionSyntax expression)
    {
        if (expression is CallExpressionSyntax { Target: NameExpressionSyntax name } call)
        {
            string normalized = name.Name.ToUpperInvariant();
            if (normalized is "返回" or "RETURN")
            {
                writer.WriteLine(call.Arguments.Count == 0 || call.Arguments[0].Value is MissingExpressionSyntax
                    ? "return;"
                    : $"return {EmitExpressionForDestination(currentMethod?.ReturnType, call.Arguments[0].Value)};");
                return;
            }
            if (normalized is "跳出循环" or "BREAK")
            {
                writer.WriteLine("break;");
                return;
            }
            if (normalized is "到循环尾" or "CONTINUE")
            {
                writer.WriteLine("continue;");
                return;
            }
            if (normalized is "抛出" or "THROW")
            {
                writer.WriteLine($"throw {EmitExpression(call.Arguments.FirstOrDefault()?.Value ?? new NewExpressionSyntax(new TypeSyntax("Exception", false, false, expression.Span), Array.Empty<ArgumentSyntax>(), expression.Span))};");
                return;
            }
            if (normalized is "重定义数组")
            {
                if (call.Arguments.Count >= 2)
                {
                    string target = EmitExpression(call.Arguments[0].Value);
                    string dimensions = string.Join(", ", call.Arguments.Skip(1).Select(argument => EmitExpression(argument.Value)));
                    writer.WriteLine($"{target}.Redim({dimensions});");
                }
                return;
            }

            if (normalized is "转换类型" or "CAST" or "安全转换类型" or "CHECKEDCAST"
                or "是否类型" or "IS" or "默认值" or "DEFAULT" or "选择" or "IIF"
                or "字符" or "到文本" or "取数组成员数" or "取文本长度" or "是否为空"
                or "到CLR数组" or "TOCLRARRAY" or "从CLR数组" or "FROMCLRARRAY")
            {
                writer.WriteLine($"global::System.GC.KeepAlive({EmitExpression(expression)});");
                return;
            }
        }

        if (expression is CallExpressionSyntax or NewExpressionSyntax)
            writer.WriteLine($"{EmitExpression(expression)};");
        else
            writer.WriteLine($"global::System.GC.KeepAlive({EmitExpression(expression)});");
    }

    private void EmitCountLoop(IndentedWriter writer, CountLoopStatementSyntax count)
    {
        string limit = Fresh("count");
        string counter = count.Counter is null ? Fresh("i") : EmitExpression(count.Counter);
        writer.WriteLine($"int {limit} = System.Convert.ToInt32({EmitExpression(count.Count)}, System.Globalization.CultureInfo.InvariantCulture);");
        using (writer.Block($"for ({(count.Counter is null ? "int " : string.Empty)}{counter} = 1; {counter} <= {limit}; {counter}++)"))
            foreach (StatementSyntax child in count.Statements) EmitStatement(writer, child);
    }

    private void EmitRangeLoop(IndentedWriter writer, RangeLoopStatementSyntax range)
    {
        string end = Fresh("end");
        string step = Fresh("step");
        string variable = range.Variable is null ? Fresh("value") : EmitExpression(range.Variable);
        TypeSyntax variableType = range.Variable is null
            ? new TypeSyntax("双精度小数型", false, false, range.Span)
            : ResolveExpressionType(range.Variable) ?? new TypeSyntax("双精度小数型", false, false, range.Span);
        string type = TypeText(variableType);
        string startValue = $"unchecked(({type})({EmitExpression(range.Start)}))";
        string endValue = $"unchecked(({type})({EmitExpression(range.End)}))";
        string stepValue = $"unchecked(({type})({EmitExpression(range.Step ?? new LiteralExpressionSyntax(1L, "1", range.Span))}))";
        writer.WriteLine($"{type} {end} = {endValue};");
        writer.WriteLine($"{type} {step} = {stepValue};");
        writer.WriteLine($"if ({step} == 0) throw new global::System.ArgumentOutOfRangeException(\"step\", \"变量循环步长不能为零。\");");
        string increment = $"{variable} = unchecked(({type})({variable} + {step}))";
        using (writer.Block($"for ({(range.Variable is null ? type + " " : string.Empty)}{variable} = {startValue}; {step} >= 0 ? {variable} <= {end} : {variable} >= {end}; {increment})"))
            foreach (StatementSyntax child in range.Statements) EmitStatement(writer, child);
    }

    private void EmitTemporarySet(IndentedWriter writer, TemporarySetStatementSyntax temporary)
    {
        string target = EmitExpression(temporary.Target);
        string old = Fresh("old");
        writer.WriteLine($"var {old} = {target};");
        writer.WriteLine("try");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"{target} = {EmitExpression(temporary.Value)};");
        foreach (StatementSyntax child in temporary.Statements) EmitStatement(writer, child);
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine("finally");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"{target} = {old};");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private string EmitExpression(ExpressionSyntax expression) => expression switch
    {
        MissingExpressionSyntax => "default",
        LiteralExpressionSyntax literal => EmitLiteral(literal),
        InterpolatedStringExpressionSyntax interpolated => EmitInterpolatedString(interpolated),
        NameExpressionSyntax name => EmitName(name.Name),
        ConstantExpressionSyntax constant => EmitConstant(constant),
        UnaryExpressionSyntax unary => $"({unary.Operator}{EmitExpression(unary.Operand)})",
        BinaryExpressionSyntax { Operator: "~=" } binary => $"global::EPLab.Runtime.EplRuntime.ApproximatelyEqual({EmitExpression(binary.Left)}, {EmitExpression(binary.Right)})",
        BinaryExpressionSyntax { Operator: "\\" } binary => $"({EmitExpression(binary.Left)} / {EmitExpression(binary.Right)})",
        BinaryExpressionSyntax binary => $"({EmitExpression(binary.Left)} {binary.Operator} {EmitExpression(binary.Right)})",
        MemberAccessExpressionSyntax member => $"{EmitExpression(member.Target)}{(member.NullConditional ? "?." : ".")}{EmitMemberName(member.MemberName, member.Target)}",
        CallExpressionSyntax call => EmitCall(call),
        IndexExpressionSyntax index => $"{EmitExpression(index.Target)}[{string.Join(", ", index.Indices.Select(EmitExpression))}]",
        ArrayLiteralExpressionSyntax array => EmitArrayLiteral(array),
        DelegateExpressionSyntax method => Identifier(ResolveDeclaredValueName(method.MethodName) ?? method.MethodName),
        TypeTestExpressionSyntax test => $"({EmitExpression(test.Value)} is {(test.Negated ? "not " : string.Empty)}{TypeText(test.Type)})",
        ConversionExpressionSyntax conversion => $"(({TypeText(conversion.Type)}){EmitExpression(conversion.Value)})",
        NewExpressionSyntax creation => $"new {TypeText(creation.Type)}({string.Join(", ", creation.Arguments.Select(EmitArgument))})",
        _ => "default",
    };

    private string EmitLiteral(LiteralExpressionSyntax literal)
    {
        if (literal.Value is null)
            return "null";
        if (literal.Value is bool boolean)
            return boolean ? "true" : "false";
        if (literal.Value is long integer)
        {
            string text = integer.ToString(CultureInfo.InvariantCulture);
            bool forcedLong = literal.RawText.EndsWith("L", StringComparison.OrdinalIgnoreCase)
                && !literal.RawText.EndsWith("UL", StringComparison.OrdinalIgnoreCase);
            return forcedLong || integer is > int.MaxValue or < int.MinValue ? text + "L" : text;
        }
        if (literal.Value is uint unsignedInteger)
            return unsignedInteger.ToString(CultureInfo.InvariantCulture) + "U";
        if (literal.Value is ulong unsignedLong)
            return unsignedLong.ToString(CultureInfo.InvariantCulture) + "UL";
        if (literal.Value is float single)
        {
            if (float.IsNaN(single)) return "float.NaN";
            if (float.IsPositiveInfinity(single)) return "float.PositiveInfinity";
            if (float.IsNegativeInfinity(single)) return "float.NegativeInfinity";
            return single.ToString("R", CultureInfo.InvariantCulture) + "F";
        }
        if (literal.Value is double number)
        {
            if (double.IsNaN(number)) return "double.NaN";
            if (double.IsPositiveInfinity(number)) return "double.PositiveInfinity";
            if (double.IsNegativeInfinity(number)) return "double.NegativeInfinity";
            return number.ToString("R", CultureInfo.InvariantCulture) + "D";
        }
        if (literal.RawText.StartsWith('['))
            return $"global::EPLab.Runtime.EplRuntime.ParseDateTime({StringLiteral(literal.RawText)})";
        return StringLiteral(Convert.ToString(literal.Value, CultureInfo.InvariantCulture) ?? string.Empty);
    }

    private string EmitInterpolatedString(InterpolatedStringExpressionSyntax interpolated)
    {
        StringBuilder result = new("$\"");
        foreach (InterpolatedPartSyntax part in interpolated.Parts)
        {
            if (part is InterpolatedTextSyntax text)
            {
                AppendInterpolatedText(result, text.Text);
                continue;
            }
            if (part is InterpolationSyntax hole)
                result.Append('{').Append(EmitExpression(hole.Expression))
                    .Append(hole.Format is null ? string.Empty : ":" + hole.Format).Append('}');
        }
        result.Append('"');
        return result.ToString();
    }

    private static void AppendInterpolatedText(StringBuilder result, string value)
    {
        result.Append(value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("{", "{{", StringComparison.Ordinal)
            .Replace("}", "}}", StringComparison.Ordinal));
    }

    private string EmitCall(CallExpressionSyntax call)
    {
        if (call.Target is NameExpressionSyntax name)
        {
            string normalized = name.Name.ToUpperInvariant();
            if (normalized is "创建对象" or "NEW")
            {
                if (call.Arguments.Count == 0)
                    return "new object()";
                string type = ExpressionAsType(call.Arguments[0].Value);
                return $"new {type}({string.Join(", ", call.Arguments.Skip(1).Select(EmitArgument))})";
            }
            if (normalized is "转换类型" or "CAST")
            {
                if (call.Arguments.Count < 2) return "default";
                return $"unchecked(({ExpressionAsType(call.Arguments[0].Value)})({EmitExpression(call.Arguments[1].Value)}))";
            }
            if (normalized is "安全转换类型" or "CHECKEDCAST")
            {
                if (call.Arguments.Count < 2) return "default";
                return $"checked(({ExpressionAsType(call.Arguments[0].Value)})({EmitExpression(call.Arguments[1].Value)}))";
            }
            if (normalized is "是否类型" or "IS")
            {
                if (call.Arguments.Count < 2) return "false";
                return $"({EmitExpression(call.Arguments[0].Value)} is {ExpressionAsType(call.Arguments[1].Value)})";
            }
            if (normalized is "默认值" or "DEFAULT")
                return call.Arguments.Count == 0 ? "default" : $"default({ExpressionAsType(call.Arguments[0].Value)})";
            if (normalized is "选择" or "IIF")
            {
                if (call.Arguments.Count < 3) return "default";
                return $"({EmitExpression(call.Arguments[0].Value)} ? {EmitExpression(call.Arguments[1].Value)} : {EmitExpression(call.Arguments[2].Value)})";
            }
            if (normalized is "字符")
                return call.Arguments.Count == 0 ? "string.Empty" : $"global::System.Convert.ToChar({EmitExpression(call.Arguments[0].Value)}).ToString()";
            if (normalized is "到文本")
                return call.Arguments.Count == 0 ? "string.Empty" : $"global::System.Convert.ToString({EmitExpression(call.Arguments[0].Value)}, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty";
            if (normalized is "取数组成员数")
                return call.Arguments.Count == 0 ? "0" : $"{EmitExpression(call.Arguments[0].Value)}.Count";
            if (normalized is "取文本长度")
                return call.Arguments.Count == 0 ? "0" : $"{EmitExpression(call.Arguments[0].Value)}.Length";
            if (normalized is "是否为空")
                return call.Arguments.Count == 0 ? "true" : $"global::EPLab.Runtime.EplRuntime.IsMissing({EmitExpression(call.Arguments[0].Value)})";
            if (normalized is "到CLR数组" or "TOCLRARRAY")
                return call.Arguments.Count == 0 ? "global::System.Array.Empty<object>()" : $"{EmitExpression(call.Arguments[0].Value)}.ToArray()";
            if (normalized is "从CLR数组" or "FROMCLRARRAY")
                return call.Arguments.Count == 0 ? "new global::EPLab.Runtime.EArray<object>()" : $"global::EPLab.Runtime.EplRuntime.ArrayFrom({EmitExpression(call.Arguments[0].Value)})";
        }

        return $"{EmitExpression(call.Target)}({string.Join(", ", call.Arguments.Select(EmitArgument))})";
    }

    private string EmitArgument(ArgumentSyntax argument)
    {
        string prefix = argument.Modifiers.HasFlag(ParameterModifiers.Out)
            ? "out "
            : argument.Modifiers.HasFlag(ParameterModifiers.ByReference) ? "ref " : string.Empty;
        string name = argument.Name is null ? string.Empty : $"{Identifier(argument.Name)}: ";
        return $"{name}{prefix}{EmitExpression(argument.Value)}";
    }

    private string EmitName(string name)
    {
        if (hoistedLocals.TryGetValue(name, out string? hoisted))
            return hoisted;
        string? declaredName = ResolveDeclaredValueName(name);
        if (declaredName is not null)
            return Identifier(declaredName);
        return name.ToUpperInvariant() switch
        {
            "日志" when program.Plugin is not null => "global::LabApi.Features.Console.Logger",
            "配置" when program.Plugin is not null => "global::__EplabHost.Config",
            "环境" => "global::System.Environment",
            _ => NormalizeQualifiedName(name),
        };
    }

    private string? ResolveDeclaredValueName(string name)
    {
        LocalVariableSyntax? local = currentMethod?.Locals.FirstOrDefault(item => item.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
        if (local is not null) return local.Name;
        ParameterSyntax? parameter = currentMethod?.Parameters.FirstOrDefault(item => item.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
        if (parameter is not null) return parameter.Name;
        FieldDeclarationSyntax? field = currentClass?.Fields.FirstOrDefault(item => item.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
        if (field is not null) return field.Name;
        MethodDeclarationSyntax? method = currentClass?.Methods.FirstOrDefault(item => item.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
        if (method is not null) return method.Name;
        return program.Declarations.Select(declaration => declaration switch
        {
            FieldDeclarationSyntax global when global.Name.Equals(name, StringComparison.OrdinalIgnoreCase) => global.Name,
            ConstantDeclarationSyntax constant when constant.Name.Equals(name, StringComparison.OrdinalIgnoreCase) => constant.Name,
            DllDeclarationSyntax dll when dll.Name.Equals(name, StringComparison.OrdinalIgnoreCase) => dll.Name,
            ClassDeclarationSyntax @class when @class.Name.Equals(name, StringComparison.OrdinalIgnoreCase) => @class.Name,
            StructDeclarationSyntax structure when structure.Name.Equals(name, StringComparison.OrdinalIgnoreCase) => structure.Name,
            EnumDeclarationSyntax enumeration when enumeration.Name.Equals(name, StringComparison.OrdinalIgnoreCase) => enumeration.Name,
            _ => null,
        }).FirstOrDefault(static item => item is not null);
    }

    private string EmitMemberName(string name, ExpressionSyntax target)
    {
        TypeSyntax? receiverType = ResolveExpressionType(target);
        if (receiverType is not null && IsUserDeclaredType(receiverType.Text))
            return Identifier(ResolveUserMemberName(receiverType.Text, name) ?? name);
        return name.ToUpperInvariant() switch
        {
            "信息" => "Info",
            "警告" => "Warn",
            "错误" => "Error",
            "数量" => "Count",
            "长度" => "Length",
            "加入" => "Add",
            "删除" => "Remove",
            "清空" => "Clear",
            _ => Identifier(name),
        };
    }

    private string EmitConstant(ConstantExpressionSyntax constant)
    {
        if (constant.TypeName is not null)
        {
            string typeName = ResolveUserDeclaredTypeName(constant.TypeName) ?? constant.TypeName;
            string memberName = ResolveUserMemberName(typeName, constant.Name) ?? constant.Name;
            return $"{NormalizeQualifiedName(typeName)}.{Identifier(memberName)}";
        }
        return constant.Name switch
        {
            "换行符" => "global::System.Environment.NewLine",
            "制表符" => "\"\\t\"",
            _ => Identifier(ResolveDeclaredValueName(constant.Name) ?? constant.Name),
        };
    }

    private string ExpressionAsType(ExpressionSyntax expression) => expression switch
    {
        NameExpressionSyntax name => TypeNameText(name.Name),
        MemberAccessExpressionSyntax member => $"{ExpressionAsType(member.Target)}.{Identifier(member.MemberName)}",
        LiteralExpressionSyntax { Value: string text } => TypeNameText(text),
        _ => EmitExpression(expression),
    };

    private string EmitParameter(ParameterSyntax parameter)
    {
        bool isParams = parameter.Modifiers.HasFlag(ParameterModifiers.Params);
        string prefix = isParams
            ? "params "
            : parameter.Modifiers.HasFlag(ParameterModifiers.Out)
                ? "out "
                : parameter.Modifiers.HasFlag(ParameterModifiers.ByReference) ? "ref " : string.Empty;
        bool optional = parameter.Modifiers.HasFlag(ParameterModifiers.Optional);
        string type = isParams
            ? TypeText(parameter.Type with { IsArray = false }) + "[]"
            : TypeText(parameter.Type, parameter.Modifiers.HasFlag(ParameterModifiers.Array));
        if (optional)
            type = $"global::EPLab.Runtime.EOptional<{type}>";
        string defaultValue = optional
            ? $" = {(parameter.DefaultValue is null ? "default" : EmitExpression(parameter.DefaultValue))}"
            : parameter.DefaultValue is null ? string.Empty : $" = {EmitExpression(parameter.DefaultValue)}";
        return $"{prefix}{type} {Identifier(parameter.Name)}{defaultValue}";
    }

    private string EmitInitializer(TypeSyntax type, ArrayShapeSyntax? shape, ExpressionSyntax? initializer)
    {
        if (initializer is not null)
        {
            if (initializer is ArrayLiteralExpressionSyntax array && (shape is not null || type.IsArray))
                return $" = {EmitArrayLiteral(array, TypeText(type with { IsArray = false }))}";
            return $" = unchecked(({TypeText(type, shape is not null)})({EmitExpression(initializer)}))";
        }
        if (shape is not null || type.IsArray)
        {
            string elementType = TypeText(type with { IsArray = false });
            string dimensions = shape is null || shape.Dynamic
                ? string.Empty
                : string.Join(", ", shape.Dimensions.Select(EmitExpression));
            return $" = new global::EPLab.Runtime.EArray<{elementType}>({dimensions})";
        }
        string mapped = TypeText(type);
        if (mapped == "string")
            return " = string.Empty";
        if (mapped == "byte[]")
            return " = global::System.Array.Empty<byte>()";
        if (mapped == "global::System.DateTime")
            return " = global::EPLab.Runtime.EplRuntime.DefaultDateTime";
        if (program.Classes.ContainsKey(type.Text))
            return " = default!";
        return " = default";
    }

    private string EmitExpressionForDestination(TypeSyntax? destinationType, ExpressionSyntax expression)
    {
        if (destinationType is not null && destinationType.IsArray && expression is ArrayLiteralExpressionSyntax array)
            return EmitArrayLiteral(array, TypeText(destinationType with { IsArray = false }));
        return EmitExpression(expression);
    }

    private string EmitArrayLiteral(ArrayLiteralExpressionSyntax array, string? elementType = null)
    {
        string generic = elementType is null ? string.Empty : $"<{elementType}>";
        if (array.Items.Count == 0 && elementType is null)
            return "new global::EPLab.Runtime.EArray<object>()";
        return $"global::EPLab.Runtime.EplRuntime.Array{generic}({string.Join(", ", array.Items.Select(EmitExpression))})";
    }

    private string TypeText(TypeSyntax type, bool forceEArray = false)
    {
        string core = TypeNameText(type.Text);
        if ((type.IsArray || forceEArray) && !core.EndsWith("[]", StringComparison.Ordinal))
            core = $"global::EPLab.Runtime.EArray<{core}>";
        if (type.IsNullable && core is not "string" and not "object" && !core.EndsWith("[]", StringComparison.Ordinal))
            core += "?";
        return core;
    }

    private string TypeNameText(string value)
    {
        value = value.Trim().Replace('《', '<').Replace('》', '>');
        int genericStart = value.IndexOf('<');
        if (genericStart >= 0 && value.EndsWith('>'))
        {
            string inner = value[(genericStart + 1)..^1];
            IReadOnlyList<string> arguments = SplitGenericArguments(inner);
            if (value[..genericStart].Trim().Equals("CLR数组", StringComparison.OrdinalIgnoreCase)
                || value[..genericStart].Trim().Equals("CLRARRAY", StringComparison.OrdinalIgnoreCase))
                return arguments.Count == 1 ? TypeNameText(arguments[0]) + "[]" : "object[]";
            string outer = TypeNameText(value[..genericStart]);
            return $"{outer}<{string.Join(", ", arguments.Select(TypeNameText))}>";
        }
        string? declaredTypeName = ResolveUserDeclaredTypeName(value);
        if (declaredTypeName is not null)
            return NormalizeQualifiedName(declaredTypeName);
        return value.ToUpperInvariant() switch
        {
            "无返回值" or "VOID" => "void",
            "字节型" or "BYTE" => "byte",
            "短整数型" or "SHORT" or "INT16" => "short",
            "整数型" or "INT" or "INT32" => "int",
            "无符号整数型" or "UINT" or "UINT32" => "uint",
            "长整数型" or "LONG" or "INT64" => "long",
            "小数型" or "FLOAT" or "SINGLE" => "float",
            "双精度小数型" or "DOUBLE" => "double",
            "逻辑型" or "BOOL" or "BOOLEAN" => "bool",
            "文本型" or "STRING" => "string",
            "字节集" => "byte[]",
            "日期时间型" or "DATETIME" => "global::System.DateTime",
            "通用型" or "OBJECT" => "object",
            "子程序指针" or "DELEGATE" => "global::System.Delegate",
            "命令上下文" or "COMMANDCONTEXT" or "EPLAB.RUNTIME.COMMANDCONTEXT" => "global::EPLab.Runtime.CommandContext",
            "列表" or "LIST" => "global::System.Collections.Generic.List",
            "字典" or "DICTIONARY" => "global::System.Collections.Generic.Dictionary",
            "集合" or "HASHSET" => "global::System.Collections.Generic.HashSet",
            "只读列表" or "IREADONLYLIST" => "global::System.Collections.Generic.IReadOnlyList",
            "玩家" => "global::LabApi.Features.Wrappers.Player",
            _ => NormalizeQualifiedName(value),
        };
    }

    private string DefaultValue(TypeSyntax type)
        => TypeText(type) == "string" ? "string.Empty" : $"default({TypeText(type)})";

    private string InferConstantType(ExpressionSyntax expression) => expression switch
    {
        LiteralExpressionSyntax { Value: bool } => "bool",
        LiteralExpressionSyntax { Value: long, RawText: var raw } when raw.EndsWith("L", StringComparison.OrdinalIgnoreCase) => "long",
        LiteralExpressionSyntax { Value: long value } => value is <= int.MaxValue and >= int.MinValue ? "int" : "long",
        LiteralExpressionSyntax { Value: uint } => "uint",
        LiteralExpressionSyntax { Value: ulong } => "ulong",
        LiteralExpressionSyntax { Value: float } => "float",
        LiteralExpressionSyntax { Value: double } => "double",
        LiteralExpressionSyntax { Value: string, RawText: var raw } when raw.StartsWith('[') => "global::System.DateTime",
        LiteralExpressionSyntax { Value: string } => "string",
        ConstantExpressionSyntax { TypeName: not null } constant => TypeNameText(constant.TypeName!),
        _ => "dynamic",
    };

    private TypeSyntax? ResolveExpressionType(ExpressionSyntax expression)
    {
        switch (expression)
        {
            case NameExpressionSyntax name:
                LocalVariableSyntax? local = currentMethod?.Locals.FirstOrDefault(item => item.Name.Equals(name.Name, StringComparison.OrdinalIgnoreCase));
                if (local is not null) return local.Type with { IsArray = local.ArrayShape is not null || local.Type.IsArray };
                ParameterSyntax? parameter = currentMethod?.Parameters.FirstOrDefault(item => item.Name.Equals(name.Name, StringComparison.OrdinalIgnoreCase));
                if (parameter is not null) return parameter.Type with { IsArray = parameter.Type.IsArray || parameter.Modifiers.HasFlag(ParameterModifiers.Array) };
                FieldDeclarationSyntax? field = currentClass?.Fields.FirstOrDefault(item => item.Name.Equals(name.Name, StringComparison.OrdinalIgnoreCase));
                if (field is not null) return field.Type with { IsArray = field.ArrayShape is not null || field.Type.IsArray };
                FieldDeclarationSyntax? global = program.Declarations.OfType<FieldDeclarationSyntax>()
                    .FirstOrDefault(item => item.Name.Equals(name.Name, StringComparison.OrdinalIgnoreCase));
                if (global is not null) return global.Type with { IsArray = global.ArrayShape is not null || global.Type.IsArray };
                string? declaredTypeName = ResolveUserDeclaredTypeName(name.Name);
                if (declaredTypeName is not null) return new TypeSyntax(declaredTypeName, false, false, name.Span);
                return null;

            case LiteralExpressionSyntax { Value: bool } literal:
                return new TypeSyntax("逻辑型", false, false, literal.Span);
            case LiteralExpressionSyntax { Value: long } literal:
                return new TypeSyntax("长整数型", false, false, literal.Span);
            case LiteralExpressionSyntax { Value: uint } literal:
                return new TypeSyntax("无符号整数型", false, false, literal.Span);
            case LiteralExpressionSyntax { Value: float } literal:
                return new TypeSyntax("小数型", false, false, literal.Span);
            case LiteralExpressionSyntax { Value: double } literal:
                return new TypeSyntax("双精度小数型", false, false, literal.Span);
            case LiteralExpressionSyntax { Value: string } literal:
                return new TypeSyntax("文本型", false, false, literal.Span);
            case InterpolatedStringExpressionSyntax interpolated:
                return new TypeSyntax("文本型", false, false, interpolated.Span);
            case ConversionExpressionSyntax conversion:
                return conversion.Type;
            case NewExpressionSyntax creation:
                return creation.Type;
            case IndexExpressionSyntax index:
                TypeSyntax? indexed = ResolveExpressionType(index.Target);
                return indexed is null ? null : indexed with { IsArray = false };
            case MemberAccessExpressionSyntax member:
                TypeSyntax? receiver = ResolveExpressionType(member.Target);
                return receiver is null ? null : ResolveUserMemberType(receiver.Text, member.MemberName);
            case CallExpressionSyntax { Target: NameExpressionSyntax callName } call:
                if (callName.Name.Equals("创建对象", StringComparison.OrdinalIgnoreCase) && call.Arguments.Count > 0)
                {
                    string typeName = call.Arguments[0].Value switch
                    {
                        NameExpressionSyntax type => type.Name,
                        LiteralExpressionSyntax { Value: string text } => text,
                        _ => string.Empty,
                    };
                    return typeName.Length == 0 ? null : new TypeSyntax(typeName, false, false, call.Span);
                }
                return currentClass?.Methods.FirstOrDefault(method => method.Name.Equals(callName.Name, StringComparison.OrdinalIgnoreCase))?.ReturnType;
            case CallExpressionSyntax { Target: MemberAccessExpressionSyntax memberCall }:
                TypeSyntax? callReceiver = ResolveExpressionType(memberCall.Target);
                return callReceiver is null ? null : ResolveUserMethodType(callReceiver.Text, memberCall.MemberName);
            default:
                return null;
        }
    }

    private TypeSyntax? ResolveUserMemberType(string typeName, string memberName)
    {
        ClassDeclarationSyntax? @class = program.Declarations.OfType<ClassDeclarationSyntax>()
            .FirstOrDefault(item => item.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase));
        FieldDeclarationSyntax? field = @class?.Fields.FirstOrDefault(item => item.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase));
        if (field is not null) return field.Type with { IsArray = field.ArrayShape is not null || field.Type.IsArray };
        StructDeclarationSyntax? structure = program.Declarations.OfType<StructDeclarationSyntax>()
            .FirstOrDefault(item => item.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase));
        FieldDeclarationSyntax? member = structure?.Members.FirstOrDefault(item => item.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase));
        return member?.Type;
    }

    private TypeSyntax? ResolveUserMethodType(string typeName, string methodName)
        => program.Declarations.OfType<ClassDeclarationSyntax>()
            .FirstOrDefault(item => item.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase))?
            .Methods.FirstOrDefault(item => item.Name.Equals(methodName, StringComparison.OrdinalIgnoreCase))?
            .ReturnType;

    private string? ResolveUserMemberName(string typeName, string memberName)
    {
        ClassDeclarationSyntax? @class = program.Declarations.OfType<ClassDeclarationSyntax>()
            .FirstOrDefault(item => item.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase));
        if (@class is not null)
        {
            FieldDeclarationSyntax? field = @class.Fields.FirstOrDefault(item => item.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase));
            if (field is not null) return field.Name;
            MethodDeclarationSyntax? method = @class.Methods.FirstOrDefault(item => item.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase));
            if (method is not null) return method.Name;
        }

        StructDeclarationSyntax? structure = program.Declarations.OfType<StructDeclarationSyntax>()
            .FirstOrDefault(item => item.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase));
        FieldDeclarationSyntax? structureMember = structure?.Members
            .FirstOrDefault(item => item.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase));
        if (structureMember is not null) return structureMember.Name;

        EnumDeclarationSyntax? enumeration = program.Declarations.OfType<EnumDeclarationSyntax>()
            .FirstOrDefault(item => item.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase));
        return enumeration?.Members.FirstOrDefault(item => item.Name.Equals(memberName, StringComparison.OrdinalIgnoreCase))?.Name;
    }

    private string? ResolveUserDeclaredTypeName(string typeName)
    {
        int generic = typeName.IndexOf('<');
        if (generic >= 0) typeName = typeName[..generic];
        return program.Declarations.Select(declaration => declaration switch
        {
            ClassDeclarationSyntax @class when @class.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase) => @class.Name,
            StructDeclarationSyntax structure when structure.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase) => structure.Name,
            EnumDeclarationSyntax enumeration when enumeration.Name.Equals(typeName, StringComparison.OrdinalIgnoreCase) => enumeration.Name,
            _ => null,
        }).FirstOrDefault(static item => item is not null);
    }

    private bool IsUserDeclaredType(string typeName) => ResolveUserDeclaredTypeName(typeName) is not null;

    private string Fresh(string hint) => $"__eplab_{hint}_{++generatedName}";

    private static bool NeedsLazyHoistedInitialization(LocalVariableSyntax local)
        => local.Initializer is not null || local.ArrayShape is not null || local.Type.IsArray;

    private string EmitLazyHoistedInitialValue(LocalVariableSyntax local)
    {
        if (local.Initializer is not null)
        {
            if (local.Initializer is ArrayLiteralExpressionSyntax array && (local.ArrayShape is not null || local.Type.IsArray))
                return EmitArrayLiteral(array, TypeText(local.Type with { IsArray = false }));
            return $"unchecked(({TypeText(local.Type, local.ArrayShape is not null)})({EmitExpression(local.Initializer)}))";
        }
        string elementType = TypeText(local.Type with { IsArray = false });
        string dimensions = local.ArrayShape is null || local.ArrayShape.Dynamic
            ? string.Empty
            : string.Join(", ", local.ArrayShape.Dimensions.Select(EmitExpression));
        return $"new global::EPLab.Runtime.EArray<{elementType}>({dimensions})";
    }

    private static string HoistedInitializerFlag(string fieldName) => fieldName + "_已初始化";

    private static bool DefinitelyReturns(IReadOnlyList<StatementSyntax> statements)
    {
        if (statements.Count == 0)
            return false;
        StatementSyntax last = statements[^1];
        if (last is ExpressionStatementSyntax { Expression: CallExpressionSyntax { Target: NameExpressionSyntax name } }
            && name.Name.Equals("返回", StringComparison.OrdinalIgnoreCase))
            return true;
        return last is IfStatementSyntax conditional
            && conditional.ElseStatements.Count > 0
            && DefinitelyReturns(conditional.ThenStatements)
            && DefinitelyReturns(conditional.ElseStatements);
    }

    private string EmitLabApiHost()
    {
        PluginSyntax plugin = program.Plugin!;
        ClassDeclarationSyntax entryClass = program.Classes[plugin.ClassName];
        IndentedWriter writer = new();
        writer.WriteLine("// <auto-generated by EPLab />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using CommandSystem;");
        writer.WriteLine("using LabApi.Features;");
        writer.WriteLine("using LabApi.Loader.Features.Plugins;");
        foreach (string import in program.NamespaceImports.Distinct(StringComparer.Ordinal))
            writer.WriteLine($"using {NormalizeQualifiedName(import)};");
        writer.WriteLine();
        using (writer.Block($"namespace {NormalizeQualifiedName(program.Project.RootNamespace)}"))
        {
            string configType = plugin.ConfigClassName is not null
                ? NormalizeQualifiedName(ResolveUserDeclaredTypeName(plugin.ConfigClassName) ?? plugin.ConfigClassName)
                : "__EplabConfig";
            if (plugin.ConfigClassName is null)
                EmitGeneratedConfig(writer);

            using (writer.Block($"public sealed class __EplabPlugin : Plugin<{configType}>"))
            {
                writer.WriteLine("internal static __EplabPlugin? Instance { get; private set; }");
                writer.WriteLine($"private {Identifier(entryClass.Name)}? entry;");
                writer.WriteLine($"internal {Identifier(entryClass.Name)} Entry => entry ?? throw new InvalidOperationException(\"The EPLab plugin entry is not enabled.\");");
                writer.WriteLine($"public override string Name => {StringLiteral(plugin.Name)};");
                writer.WriteLine($"public override string Description => {StringLiteral(plugin.Description)};");
                writer.WriteLine($"public override string Author => {StringLiteral(plugin.Author)};");
                writer.WriteLine($"public override Version Version => new Version({StringLiteral(plugin.Version)});");
                string apiVersion = plugin.RequiredApiVersion is null
                    ? "new Version(LabApiProperties.CompiledVersion)"
                    : $"new Version({StringLiteral(plugin.RequiredApiVersion)})";
                writer.WriteLine($"public override Version RequiredApiVersion => {apiVersion};");
                ConfigItemSyntax? languageItem = program.ConfigItems.FirstOrDefault(item =>
                    item.Name.Equals("language", StringComparison.OrdinalIgnoreCase)
                    || item.Name.Equals("语言", StringComparison.OrdinalIgnoreCase)
                    || item.SerializedName?.Equals("language", StringComparison.OrdinalIgnoreCase) == true);
                using (writer.Block("internal string LocalText(string chinese, string english)"))
                {
                    if (languageItem is null)
                        writer.WriteLine("return chinese;");
                    else
                        writer.WriteLine($"return string.Equals(global::System.Convert.ToString(Config.{Identifier(languageItem.Name)}), \"en\", StringComparison.OrdinalIgnoreCase) ? english : chinese;");
                }
                writer.WriteLine();

                using (writer.Block("public override void Enable()"))
                {
                    using (writer.Block("try"))
                    {
                        foreach (ConfigItemSyntax item in program.ConfigItems.Where(static item => item.Minimum is not null || item.Maximum is not null))
                        {
                            string minimum = item.Minimum is null ? "null" : $"(double?)global::System.Convert.ToDouble({EmitExpression(item.Minimum)}, global::System.Globalization.CultureInfo.InvariantCulture)";
                            string maximum = item.Maximum is null ? "null" : $"(double?)global::System.Convert.ToDouble({EmitExpression(item.Maximum)}, global::System.Globalization.CultureInfo.InvariantCulture)";
                            writer.WriteLine($"Config.{Identifier(item.Name)} = global::EPLab.Runtime.EplRuntime.ValidateRange(Config.{Identifier(item.Name)}, {minimum}, {maximum}, {EmitExpression(item.DefaultValue)});");
                        }
                        writer.WriteLine("global::__EplabHost.Config = Config;");
                        LineDirective(writer, entryClass.Span);
                        writer.WriteLine($"entry = new {Identifier(entryClass.Name)}();");
                        ResetLineDirective(writer);
                        foreach (EventBindingSyntax binding in program.EventBindings)
                        {
                            MethodDeclarationSyntax? handler = FindMethod(entryClass, binding.HandlerName);
                            LineDirective(writer, binding.Span);
                            writer.WriteLine($"{NormalizeQualifiedName(binding.EventPath)} += Entry.{Identifier(handler?.Name ?? binding.HandlerName)};");
                            ResetLineDirective(writer);
                        }
                        MethodDeclarationSyntax? enable = FindMethod(entryClass, "插件启动", "_插件启动", "Enable");
                        if (enable is not null)
                            writer.WriteLine($"Entry.{Identifier(enable.Name)}();");
                        writer.WriteLine("Instance = this;");
                    }
                    using (writer.Block("catch"))
                    {
                        writer.WriteLine("var failedEntry = entry;");
                        using (writer.Block("try"))
                        {
                            using (writer.Block("if (failedEntry is not null)"))
                            {
                                MethodDeclarationSyntax? failedDisable = FindMethod(entryClass, "插件停止", "_插件停止", "Disable");
                                if (failedDisable is not null)
                                {
                                    using (writer.Block("try"))
                                    {
                                        LineDirective(writer, failedDisable.Span);
                                        writer.WriteLine($"failedEntry.{Identifier(failedDisable.Name)}();");
                                        ResetLineDirective(writer);
                                    }
                                    using (writer.Block("catch"))
                                    {
                                        writer.WriteLine("// Preserve the original Enable exception after best-effort cleanup.");
                                    }
                                }
                                foreach (EventBindingSyntax binding in program.EventBindings.Reverse())
                                {
                                    MethodDeclarationSyntax? handler = FindMethod(entryClass, binding.HandlerName);
                                    using (writer.Block("try"))
                                    {
                                        LineDirective(writer, binding.Span);
                                        writer.WriteLine($"{NormalizeQualifiedName(binding.EventPath)} -= failedEntry.{Identifier(handler?.Name ?? binding.HandlerName)};");
                                        ResetLineDirective(writer);
                                    }
                                    using (writer.Block("catch"))
                                    {
                                        writer.WriteLine("// Keep attempting the remaining rollback steps.");
                                    }
                                }
                            }
                            using (writer.Block("try"))
                                writer.WriteLine("global::LabApi.Loader.CommandLoader.UnregisterCommands(this);");
                            using (writer.Block("catch"))
                            {
                                writer.WriteLine("// LabAPI registers commands before Enable; preserve the original failure while releasing them best-effort.");
                            }
                        }
                        using (writer.Block("finally"))
                        {
                            writer.WriteLine("entry = null;");
                            writer.WriteLine("global::__EplabHost.Config = null;");
                            writer.WriteLine("Instance = null;");
                        }
                        writer.WriteLine("throw;");
                    }
                }

                using (writer.Block("public override void Disable()"))
                {
                    writer.WriteLine("var activeEntry = entry;");
                    using (writer.Block("try"))
                    {
                        MethodDeclarationSyntax? disable = FindMethod(entryClass, "插件停止", "_插件停止", "Disable");
                        if (disable is not null)
                        {
                            using (writer.Block("if (activeEntry is not null)"))
                                writer.WriteLine($"activeEntry.{Identifier(disable.Name)}();");
                        }
                    }
                    using (writer.Block("finally"))
                    {
                        using (writer.Block("try"))
                        {
                            using (writer.Block("if (activeEntry is not null)"))
                            {
                                foreach (EventBindingSyntax binding in program.EventBindings.Reverse())
                                {
                                    MethodDeclarationSyntax? handler = FindMethod(entryClass, binding.HandlerName);
                                    using (writer.Block("try"))
                                    {
                                        LineDirective(writer, binding.Span);
                                        writer.WriteLine($"{NormalizeQualifiedName(binding.EventPath)} -= activeEntry.{Identifier(handler?.Name ?? binding.HandlerName)};");
                                        ResetLineDirective(writer);
                                    }
                                    using (writer.Block("catch"))
                                    {
                                        writer.WriteLine("// Keep attempting cleanup and always clear published state.");
                                    }
                                }
                            }
                            using (writer.Block("try"))
                                writer.WriteLine("global::LabApi.Loader.CommandLoader.UnregisterCommands(this);");
                            using (writer.Block("catch"))
                            {
                                writer.WriteLine("// Repeated or externally-managed Disable calls still clear the generated host safely.");
                            }
                        }
                        using (writer.Block("finally"))
                        {
                            writer.WriteLine("entry = null;");
                            writer.WriteLine("global::__EplabHost.Config = null;");
                            writer.WriteLine("Instance = null;");
                        }
                    }
                }
            }
            writer.WriteLine();

            foreach ((CommandBindingSyntax binding, int index) in program.CommandBindings.Select((item, index) => (item, index)))
                EmitCommandAdapter(writer, binding, index, entryClass);
        }
        return writer.ToString();
    }

    private void EmitGeneratedConfig(IndentedWriter writer)
    {
        using (writer.Block("public sealed class __EplabConfig"))
        {
            foreach (ConfigItemSyntax item in program.ConfigItems)
            {
                LineDirective(writer, item.Span);
                if (item.SerializedName is not null)
                    writer.WriteLine($"[global::YamlDotNet.Serialization.YamlMember(Alias = {StringLiteral(item.SerializedName)})]");
                string? description = item.DescriptionChinese ?? item.DescriptionEnglish;
                if (description is not null)
                    writer.WriteLine($"[global::System.ComponentModel.Description({StringLiteral(description)})]");
                writer.WriteLine($"public {TypeText(item.Type)} {Identifier(item.Name)} {{ get; set; }} = unchecked(({TypeText(item.Type)})({EmitExpressionForDestination(item.Type, item.DefaultValue)}));");
                ResetLineDirective(writer);
            }
        }
        writer.WriteLine();
    }

    private void EmitCommandAdapter(IndentedWriter writer, CommandBindingSyntax binding, int index, ClassDeclarationSyntax entryClass)
    {
        string handlerType = binding.Kind switch
        {
            CommandKind.RemoteAdmin => "RemoteAdminCommandHandler",
            CommandKind.PlayerConsole => "ClientCommandHandler",
            _ => "GameConsoleCommandHandler",
        };
        LineDirective(writer, binding.Span);
        writer.WriteLine($"[CommandHandler(typeof({handlerType}))]");
        using (writer.Block($"public sealed class __EplabCommand{index} : ICommand"))
        {
            writer.WriteLine($"public string Command => {StringLiteral(binding.Name)};");
            string aliases = binding.Aliases.Count == 0
                ? "global::System.Array.Empty<string>()"
                : $"new[] {{ {string.Join(", ", binding.Aliases.Select(StringLiteral))} }}";
            writer.WriteLine($"public string[] Aliases {{ get; }} = {aliases};");
            writer.WriteLine($"public string Description => {StringLiteral(binding.Description)};");
            using (writer.Block("public bool Execute(ArraySegment<string> arguments, ICommandSender sender, out string response)"))
            {
                writer.WriteLine("var plugin = __EplabPlugin.Instance;");
                writer.WriteLine("if (plugin is null) { response = \"插件未加载。\"; return false; }");
                if (binding.Permission is not null)
                {
                    writer.WriteLine("if (!sender.CheckPermission(PlayerPermissions." + Identifier(binding.Permission) + ", out _)) { response = plugin.LocalText(\"权限不足。\", \"Permission denied.\"); return false; }");
                }
                writer.WriteLine("var context = new global::EPLab.Runtime.CommandContext(arguments, sender);");
                MethodDeclarationSyntax? handler = FindMethod(entryClass, binding.HandlerName);
                bool returnsBool = handler is not null && TypeText(handler.ReturnType) == "bool";
                string handlerName = handler?.Name ?? binding.HandlerName;
                if (returnsBool)
                    writer.WriteLine($"bool success = plugin.Entry.{Identifier(handlerName)}(context);");
                else
                {
                    writer.WriteLine($"plugin.Entry.{Identifier(handlerName)}(context);");
                    writer.WriteLine("bool success = context.Success;");
                }
                writer.WriteLine("response = context.Response;");
                writer.WriteLine("return success;");
            }
        }
        ResetLineDirective(writer);
        writer.WriteLine();
    }

    private string EmitRuntime()
    {
        bool labApi = program.Plugin is not null;
        StringBuilder source = new();
        source.AppendLine("// <auto-generated by EPLab />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.Globalization;");
        if (labApi)
            source.AppendLine("using CommandSystem;");
        source.AppendLine("namespace EPLab.Runtime");
        source.AppendLine("{");
        source.AppendLine(RuntimeCoreSource);
        if (labApi)
            source.AppendLine(CommandContextSource);
        source.AppendLine("}");
        source.AppendLine("internal static class __EplabHost { internal static dynamic? Config { get; set; } }");
        return source.ToString();
    }

    private static MethodDeclarationSyntax? FindMethod(ClassDeclarationSyntax @class, params string[] names)
        => @class.Methods.FirstOrDefault(method => names.Any(name => method.Name.Equals(name, StringComparison.OrdinalIgnoreCase)));

    private string MethodVisibilityText(MethodDeclarationSyntax method)
    {
        bool onEntryClass = program.Plugin is not null
            && currentClass is not null
            && currentClass.Name.Equals(program.Plugin.ClassName, StringComparison.OrdinalIgnoreCase);
        bool entryMethod = onEntryClass
            && (program.EventBindings.Any(binding => binding.HandlerName.Equals(method.Name, StringComparison.OrdinalIgnoreCase))
                || program.CommandBindings.Any(binding => binding.HandlerName.Equals(method.Name, StringComparison.OrdinalIgnoreCase))
                || IsEntryLifecycleName(method.Name));
        bool entryConstructor = onEntryClass
            && method.Parameters.Count == 0
            && (method.Modifiers.HasFlag(DeclarationModifiers.Constructor)
                || method.Name.Equals("_初始化", StringComparison.OrdinalIgnoreCase));
        return (entryMethod || entryConstructor) && method.Visibility is Visibility.Private or Visibility.Protected
            ? "internal"
            : VisibilityText(method.Visibility);
    }

    private static bool IsEntryLifecycleName(string name)
        => new[] { "插件启动", "_插件启动", "Enable", "插件停止", "_插件停止", "Disable" }
            .Any(candidate => candidate.Equals(name, StringComparison.OrdinalIgnoreCase));

    private static string DeclarationModifiersText(DeclarationModifiers modifiers)
    {
        List<string> values = new();
        if (modifiers.HasFlag(DeclarationModifiers.Static)) values.Add("static");
        if (modifiers.HasFlag(DeclarationModifiers.ReadOnly)) values.Add("readonly");
        if (modifiers.HasFlag(DeclarationModifiers.Abstract)) values.Add("abstract");
        if (modifiers.HasFlag(DeclarationModifiers.Virtual)) values.Add("virtual");
        if (modifiers.HasFlag(DeclarationModifiers.Override)) values.Add("override");
        if (modifiers.HasFlag(DeclarationModifiers.Sealed)) values.Add("sealed");
        if (modifiers.HasFlag(DeclarationModifiers.Async)) values.Add("async");
        if (modifiers.HasFlag(DeclarationModifiers.Partial)) values.Add("partial");
        return values.Count == 0 ? string.Empty : string.Join(' ', values) + " ";
    }

    private static string VisibilityText(Visibility visibility) => visibility switch
    {
        Visibility.Public => "public",
        Visibility.Protected => "protected",
        Visibility.Internal => "internal",
        _ => "private",
    };

    private static string Identifier(string value)
    {
        value = value.Trim();
        if (value.Length == 0)
            return "__missing";
        return CSharpKeywords.Contains(value) ? "@" + value : value;
    }

    private static string NormalizeQualifiedName(string value)
        => string.Join('.', value.Replace("::", ".", StringComparison.Ordinal).Split('.').Select(Identifier));

    private static string StringLiteral(string value)
        => "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal) + "\"";

    private static string InterpolatedStringLiteral(string value)
        => "$\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";

    private static IReadOnlyList<string> SplitGenericArguments(string value)
    {
        List<string> result = new();
        int nesting = 0;
        int start = 0;
        for (int i = 0; i < value.Length; i++)
        {
            if (value[i] == '<') nesting++;
            else if (value[i] == '>') nesting--;
            else if (value[i] == ',' && nesting == 0)
            {
                result.Add(value[start..i].Trim());
                start = i + 1;
            }
        }
        result.Add(value[start..].Trim());
        return result;
    }

    private static void LineDirective(IndentedWriter writer, SourceSpan span)
        => writer.WriteLine($"#line {span.Line} {StringLiteral(Path.GetFullPath(span.FilePath))}");

    private static void ResetLineDirective(IndentedWriter writer) => writer.WriteLine("#line default");

    private static readonly string[] DefaultImports =
    {
        "System",
        "System.Collections.Generic",
        "System.Linq",
        "EPLab.Runtime",
    };

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
        "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
        "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
        "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
        "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref",
        "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while",
    };

    private const string RuntimeCoreSource = @"
    public readonly struct EOptional<T>
    {
        private readonly T? value;
        public EOptional(T value) { this.value = value; HasValue = true; }
        public bool HasValue { get; }
        public T Value => HasValue ? value! : throw new InvalidOperationException(""可空值为空。"");
        public static implicit operator EOptional<T>(T value) => new EOptional<T>(value);
        public static implicit operator T(EOptional<T> value) => value.Value;
    }

    public sealed class EArray<T> : IEnumerable<T>
    {
        private T[] values;
        private int[] dimensions;

        public EArray(params int[] dimensions)
        {
            this.dimensions = dimensions == null ? Array.Empty<int>() : (int[])dimensions.Clone();
            values = new T[CalculateLength(this.dimensions)];
        }

        public EArray(IEnumerable<T> values)
        {
            this.values = values == null ? Array.Empty<T>() : new List<T>(values).ToArray();
            dimensions = new[] { this.values.Length };
        }

        public int Count => values.Length;
        public int Length => values.Length;
        public IReadOnlyList<int> Dimensions => dimensions;

        public T this[params int[] indices]
        {
            get => values[Flatten(indices)];
            set => values[Flatten(indices)] = value;
        }

        public void Add(T value)
        {
            if (dimensions.Length > 1) throw new InvalidOperationException(""只有一维数组可以增加成员。"");
            Array.Resize(ref values, values.Length + 1);
            values[values.Length - 1] = value;
            dimensions = new[] { values.Length };
        }

        public bool Remove(T value)
        {
            int index = Array.IndexOf(values, value);
            if (index < 0) return false;
            var next = new T[values.Length - 1];
            if (index > 0) Array.Copy(values, 0, next, 0, index);
            if (index < values.Length - 1) Array.Copy(values, index + 1, next, index, values.Length - index - 1);
            values = next;
            dimensions = new[] { values.Length };
            return true;
        }

        public void Clear()
        {
            values = Array.Empty<T>();
            dimensions = Array.Empty<int>();
        }

        public void Redim(params int[] newDimensions)
        {
            var next = new T[CalculateLength(newDimensions)];
            Array.Copy(values, next, Math.Min(values.Length, next.Length));
            values = next;
            dimensions = (int[])newDimensions.Clone();
        }

        public IEnumerator<T> GetEnumerator() => ((IEnumerable<T>)values).GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        public T[] ToArray() => (T[])values.Clone();

        private int Flatten(int[] indices)
        {
            if (indices == null || indices.Length == 0) throw new IndexOutOfRangeException(""易数组下标从 1 开始。"");
            if (dimensions.Length == 0 && indices.Length == 1) throw new IndexOutOfRangeException();
            if (indices.Length == 1 && dimensions.Length > 1)
            {
                int flat = indices[0] - 1;
                if ((uint)flat >= (uint)values.Length) throw new IndexOutOfRangeException();
                return flat;
            }
            if (indices.Length != dimensions.Length) throw new IndexOutOfRangeException(""数组下标维数不正确。"");
            int result = 0;
            for (int i = 0; i < indices.Length; i++)
            {
                int zeroBased = indices[i] - 1;
                if ((uint)zeroBased >= (uint)dimensions[i]) throw new IndexOutOfRangeException();
                result = checked(result * dimensions[i] + zeroBased);
            }
            return result;
        }

        private static int CalculateLength(int[] dimensions)
        {
            if (dimensions == null || dimensions.Length == 0) return 0;
            int length = 1;
            foreach (int dimension in dimensions)
            {
                if (dimension < 0) throw new ArgumentOutOfRangeException(nameof(dimensions));
                length = checked(length * dimension);
            }
            return length;
        }
    }

    public static class EplRuntime
    {
        public static readonly DateTime DefaultDateTime = new DateTime(1899, 12, 30, 0, 0, 0, DateTimeKind.Unspecified);
        public static EArray<T> Array<T>(params T[] values) => new EArray<T>(values);
        public static EArray<T> ArrayFrom<T>(IEnumerable<T> values) => new EArray<T>(values);
        public static bool ApproximatelyEqual(object? left, object? right)
        {
            string first = Convert.ToString(left, CultureInfo.InvariantCulture) ?? string.Empty;
            string prefix = Convert.ToString(right, CultureInfo.InvariantCulture) ?? string.Empty;
            return first.StartsWith(prefix, StringComparison.Ordinal);
        }
        public static bool IsMissing<T>(EOptional<T> value) => !value.HasValue;
        public static bool IsMissing(object? value) => value is null;
        public static T ValidateRange<T>(T value, double? minimum, double? maximum, T fallback)
        {
            try
            {
                double number = Convert.ToDouble(value, CultureInfo.InvariantCulture);
                if (double.IsNaN(number) || double.IsInfinity(number)) return fallback;
                if (minimum.HasValue && number < minimum.Value) number = minimum.Value;
                if (maximum.HasValue && number > maximum.Value) number = maximum.Value;
                return (T)Convert.ChangeType(number, typeof(T), CultureInfo.InvariantCulture);
            }
            catch
            {
                return fallback;
            }
        }
        public static DateTime ParseDateTime(string text)
        {
            string value = text.Trim('[', ']');
            string[] formats =
            {
                ""yyyy年M月d日H时m分s秒"", ""yyyy年M月d日"",
                ""yyyy/M/d/H/m/s"", ""yyyy/M/d/H:m:s"", ""yyyy/M/d H:m:s"", ""yyyy/M/d"",
                ""yyyy-M-d-H-m-s"", ""yyyy-M-d-H:m:s"", ""yyyy-M-d H:m:s"", ""yyyy-M-d"",
                ""yyyyMMddHHmmss"", ""yyyyMMdd"",
            };
            return DateTime.ParseExact(value, formats, CultureInfo.GetCultureInfo(""zh-CN""), DateTimeStyles.AllowWhiteSpaces);
        }
    }
";

    private const string CommandContextSource = @"
    public sealed class CommandContext
    {
        public CommandContext(ArraySegment<string> arguments, ICommandSender sender)
        {
            Arguments = new EArray<string>(arguments);
            Sender = sender;
        }
        public EArray<string> Arguments { get; }
        public EArray<string> 参数 => Arguments;
        public ICommandSender Sender { get; }
        public ICommandSender 发送者 => Sender;
        public string Response { get; set; } = string.Empty;
        public string 回复 { get => Response; set => Response = value ?? string.Empty; }
        public bool Success { get; set; }
        public bool 成功 { get => Success; set => Success = value; }
    }
";
}
